"""Idempotent README section injection.

The engine only ever writes *between* its own markers. Anything a human writes
outside them is preserved byte-for-byte — running the job a thousand times
produces the same file as running it once.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone

from typing import Any, Mapping

from .heatmap import Heatmap, weekday_table
from .metrics import Snapshot

START = "<!-- PROFILE-ENGINE:START -->"
END = "<!-- PROFILE-ENGINE:END -->"

_BLOCK = re.compile(
    re.escape(START) + r".*?" + re.escape(END),
    re.DOTALL,
)


class MarkerError(RuntimeError):
    """Raised when the README markers are missing or malformed."""


def render_section(
    snapshot: Snapshot,
    *,
    generated_at: datetime | None = None,
    heatmap: Heatmap | None = None,
    report_url: str | None = None,
    heatmap_asset: str = "assets/generated/heatmap.svg",
    cache_stats: Mapping[str, Any] | None = None,
) -> str:
    """Build the markdown block placed between the markers.

    Optional inputs degrade gracefully: without a heatmap or report URL the
    block renders exactly as it did before, so old call sites keep working.
    """
    stamp = (generated_at or datetime.now(tz=timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    streak = snapshot.streak

    table = "\n".join(
        f"| [`{repo.name}`]({repo.url}) | {repo.primary_language} | {repo.commits} | "
        f"{repo.stars} | {repo.days_since_push}d ago |"
        for repo in snapshot.top_repositories
    ) or "| _no repositories_ | – | – | – | – |"

    languages = " · ".join(
        f"**{share.name}** {share.percent:.1f}%" for share in snapshot.languages[:6]
    ) or "_no language data_"

    heat_block = ""
    if heatmap is not None and heatmap.total > 0:
        heat_block = f"""### 🔥 Commit distribution — weekday × week

<div align="center">

<img src="{heatmap_asset}" alt="Commit heatmap by weekday and week" width="96%" />

</div>

| Weekday | Distribution | Contributions | Share |
| --- | --- | --- | --- |
{weekday_table(heatmap)}

| Rhythm signal | Value |
| --- | --- |
| Window | `{heatmap.start.isoformat()}` → `{heatmap.end.isoformat()}` ({heatmap.weeks} weeks) |
| Days with activity | **{heatmap.active_days}** ({heatmap.consistency}% of the window) |
| Daily average | **{heatmap.daily_average}** contributions |
| Peak weekday | **{heatmap.peak_weekday}** · quietest **{heatmap.quietest_weekday}** |
| Weekend share | **{heatmap.weekend_share}%** |
| Busiest single day | **{heatmap.busiest_day_count}** on `{heatmap.busiest_day.isoformat() if heatmap.busiest_day else "—"}` |

"""

    report_block = ""
    if report_url:
        json_url = report_url.rsplit("/", 1)[0] + "/profile-report.json"
        report_block = (
            f"### 📈 Full interactive report\n\n"
            f"**[Open the live dashboard →]({report_url})** · "
            f"machine-readable [`JSON`]({json_url}) · rebuilt on every run.\n\n"
        )

    cache_block = ""
    if cache_stats:
        cache_block = (
            "<sub>Pipeline health · cache hit rate "
            f"<b>{cache_stats.get('hit_rate_percent', 0)}%</b> "
            f"({cache_stats.get('hits', 0)} hit / {cache_stats.get('misses', 0)} miss)</sub>\n\n"
        )

    return f"""{START}
<!-- Generated by tools/profile-engine. Do not edit by hand; edits inside this block are overwritten. -->

<div align="center">

<img src="assets/generated/stats.svg" alt="GitHub engineering statistics" width="47%" />
<img src="assets/generated/languages.svg" alt="Language distribution" width="47%" />

</div>

### 📊 Live engineering metrics

| Metric | Value |
| --- | --- |
| Public repositories | **{snapshot.public_repos}** |
| Total commits | **{snapshot.total_commits}** |
| Stars earned | **{snapshot.total_stars}** |
| Forks | **{snapshot.total_forks}** |
| Shipped in the last 30 days | **{snapshot.active_repos}** repositories |
| Contribution streak | **{streak.current}** days (longest **{streak.longest}**) |
| Contributions this year | **{streak.total}** |
| Engineering footprint score | **{snapshot.impact_score}/100** |

### 🧠 Language distribution

{languages}

{heat_block}### 🚀 Most active work

| Repository | Language | Commits | Stars | Last push |
| --- | --- | --- | --- | --- |
{table}

{report_block}{cache_block}<sub>Recomputed automatically by a GitHub Actions workflow · last run <code>{stamp}</code></sub>

{END}"""


def inject(readme: str, section: str) -> str:
    """Replace the marked block, or append it when the markers are absent."""
    if START not in readme:
        separator = "" if readme.endswith("\n\n") else ("\n" if readme.endswith("\n") else "\n\n")
        return f"{readme}{separator}{section}\n"
    if END not in readme:
        raise MarkerError("Found the start marker without a matching end marker.")
    if readme.index(END) < readme.index(START):
        raise MarkerError("README markers are inverted.")
    return _BLOCK.sub(lambda _: section, readme, count=1)
