"""Idempotent README section injection.

The engine only ever writes *between* its own markers. Anything a human writes
outside them is preserved byte-for-byte — running the job a thousand times
produces the same file as running it once.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone

from .metrics import Snapshot

START = "<!-- PROFILE-ENGINE:START -->"
END = "<!-- PROFILE-ENGINE:END -->"

_BLOCK = re.compile(
    re.escape(START) + r".*?" + re.escape(END),
    re.DOTALL,
)


class MarkerError(RuntimeError):
    """Raised when the README markers are missing or malformed."""


def render_section(snapshot: Snapshot, *, generated_at: datetime | None = None) -> str:
    """Build the markdown block placed between the markers."""
    stamp = (generated_at or datetime.now(tz=timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    streak = snapshot.streak

    table = "\n".join(
        f"| [`{repo.name}`]({repo.url}) | {repo.primary_language} | {repo.commits} | "
        f"{repo.stars} | {repo.days_since_push}d ago |"
        for repo in snapshot.top_repositories
    ) or "| _no repositories_ | – | – | – | – |"

    languages = " · ".join(
        f"**{share.name}** {share.percent:.1f}%" for share in snapshot.languages[:6]
    ) or "_no language data_"

    return f"""{START}
<!-- Generated by tools/profile-engine. Do not edit by hand; edits inside this block are overwritten. -->

<div align="center">

<img src="assets/generated/stats.svg" alt="GitHub engineering statistics" width="47%" />
<img src="assets/generated/languages.svg" alt="Language distribution" width="47%" />

</div>

### 📊 Live engineering metrics

| Metric | Value |
| --- | --- |
| Public repositories | **{snapshot.public_repos}** |
| Total commits | **{snapshot.total_commits}** |
| Stars earned | **{snapshot.total_stars}** |
| Forks | **{snapshot.total_forks}** |
| Shipped in the last 30 days | **{snapshot.active_repos}** repositories |
| Contribution streak | **{streak.current}** days (longest **{streak.longest}**) |
| Contributions this year | **{streak.total}** |
| Engineering footprint score | **{snapshot.impact_score}/100** |

### 🧠 Language distribution

{languages}

### 🚀 Most active work

| Repository | Language | Commits | Stars | Last push |
| --- | --- | --- | --- | --- |
{table}

<sub>Recomputed automatically by a GitHub Actions workflow · last run <code>{stamp}</code></sub>

{END}"""


def inject(readme: str, section: str) -> str:
    """Replace the marked block, or append it when the markers are absent."""
    if START not in readme:
        separator = "" if readme.endswith("\n\n") else ("\n" if readme.endswith("\n") else "\n\n")
        return f"{readme}{separator}{section}\n"
    if END not in readme:
        raise MarkerError("Found the start marker without a matching end marker.")
    if readme.index(END) < readme.index(START):
        raise MarkerError("README markers are inverted.")
    return _BLOCK.sub(lambda _: section, readme, count=1)
